package com.finny.pet.ui.games

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.gestures.detectDragGesturesAfterLongPress
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.animation.core.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.boundsInRoot
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.zIndex
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.hilt.navigation.compose.hiltViewModel
import com.finny.pet.ui.components.*

@Composable private fun GameFrame(title:String,subtitle:String,level:Int,onBack:()->Unit,content: @Composable ColumnScope.() -> Unit){
    val id=when(title){"Весы"->"scales";"Приоритеты"->"priorities";"Копилка"->"piggy";"Цель"->"goal";"Магазин"->"shop";else->"change"};val info=EducationalGameCatalog.get(id)
    val accent=when(id){"scales"->Color(0xFF436FCE);"priorities"->Color(0xFFE78B36);"piggy"->Color(0xFF8E64D4);"goal"->Color(0xFF48A77C);"shop"->Color(0xFFE45F78);else->Color(0xFF357FB3)}
    Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(accent.copy(.22f),Color(0xFFFFF8E8),Color(0xFFF4E7FF))))){
        Box(Modifier.size(180.dp).offset(x=(-55).dp,y=(-60).dp).background(Color.White.copy(.35f),CircleShape))
        Box(Modifier.size(130.dp).align(Alignment.BottomEnd).offset(x=35.dp,y=35.dp).background(Color(0xFFFFD86B).copy(.25f),CircleShape))
        LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),verticalArrangement=Arrangement.spacedBy(12.dp),contentPadding=PaddingValues(top=12.dp,bottom=28.dp)){
            item{
                Surface(color=accent,shape=RoundedCornerShape(26.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color.White.copy(.45f)),shadowElevation=10.dp){
                    Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically){
                        IconButton(onClick=onBack,Modifier.size(48.dp)){Icon(androidx.compose.material.icons.Icons.Default.ArrowBack,"Назад",tint=Color.White)}
                        Surface(color=Color(0x33FFFFFF),shape=CircleShape){Icon(gameIcon(title),null,Modifier.padding(10.dp).size(28.dp),tint=Color.White)}
                        Spacer(Modifier.width(11.dp))
                        Column(Modifier.weight(1f)){Text(title,fontSize=25.sp,fontWeight=FontWeight.ExtraBold,color=Color.White,maxLines=1,overflow=TextOverflow.Ellipsis);Text(subtitle,fontSize=13.sp,color=Color.White.copy(.9f),maxLines=2,overflow=TextOverflow.Ellipsis)};Spacer(Modifier.width(6.dp));Surface(shape=CircleShape,color=Color(0x33FFFFFF)){Text("Ур. $level",Modifier.padding(horizontal=10.dp,vertical=6.dp),color=Color.White,fontWeight=FontWeight.Black,maxLines=1,softWrap=false)}
                    }
                }
            }
            item{Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),color=Color.White.copy(.98f),border=androidx.compose.foundation.BorderStroke(1.dp,accent.copy(.25f)),shadowElevation=5.dp){Row(Modifier.fillMaxWidth().padding(13.dp),verticalAlignment=Alignment.Top){Text("💡",fontSize=23.sp);Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text("Как играть",fontWeight=FontWeight.Black,color=accent);Text(info.instruction,fontSize=14.sp,lineHeight=19.sp,color=Color(0xFF53627A))}}}}
            item{Column(verticalArrangement=Arrangement.spacedBy(12.dp),content=content)}
        }
    }
}
private fun gameIcon(title:String):ImageVector=when(title){"Весы"->Icons.Default.Balance;"Приоритеты"->Icons.Default.FilterAlt;"Копилка"->Icons.Default.Savings;"Цель"->Icons.Default.Flag;"Магазин"->Icons.Default.ShoppingCart;else->Icons.Default.Calculate}

@Composable fun ScalesScreen(onBack:()->Unit,onDone:(Int)->Unit,vm:ScalesViewModel=hiltViewModel()){val s by vm.state.collectAsStateWithLifecycle();if(s.message.isNotEmpty()&&s.message!="Верно!")FeedbackDialog("Давай разберёмся",s.message,vm::clearMessage);var selectedId by remember(s.level){mutableStateOf<String?>(null)};val selected=s.cards.firstOrNull{it.id==selectedId};var incomeBounds by remember{mutableStateOf(Rect.Zero)};var expenseBounds by remember{mutableStateOf(Rect.Zero)};val beamTarget=((s.expenses-s.income).coerceIn(-70,70)/5.4f).coerceIn(-13f,13f);val beamAngle by animateFloatAsState(beamTarget,spring(dampingRatio=Spring.DampingRatioMediumBouncy,stiffness=Spring.StiffnessLow),label="scalePhysics");GameFrame("Весы","Перетаскивай карточки на чаши",s.level,onBack){
    LaunchedEffect(s.cards.isEmpty()){if(s.cards.isEmpty()){kotlinx.coroutines.delay(650);vm.finish(onDone)}}
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){GameStat("+","Доходы",s.income.toString(),Color(0xFFDFF7EB),Modifier.weight(1f));GameStat("−","Расходы",s.expenses.toString(),Color(0xFFFFE2E1),Modifier.weight(1f));GameStat("=","Баланс",(s.income-s.expenses).toString(),Color(0xFFE5EDFF),Modifier.weight(1f))}
    Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(28.dp),color=Color(0xFFFFE59A),shadowElevation=9.dp){Column(Modifier.padding(horizontal=12.dp,vertical=9.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(3.dp)){Text("ФИНАНСОВЫЕ ВЕСЫ",color=Color(0xFF754D08),fontWeight=FontWeight.Black);Text("Зажми карточку и перенеси её на чашу",fontSize=11.sp,color=Color(0xFF7A5A20));Box(Modifier.fillMaxWidth().height(152.dp)){Box(Modifier.align(Alignment.Center).width(238.dp).height(10.dp).graphicsLayer{rotationZ=beamAngle}.background(Color(0xFF64748B),RoundedCornerShape(6.dp)));Box(Modifier.align(Alignment.Center).width(16.dp).height(76.dp).offset(y=38.dp).background(Color(0xFF2563EB),RoundedCornerShape(8.dp)));Surface(Modifier.align(Alignment.CenterStart).offset(y=(-beamAngle*.62f).dp).width(137.dp).height(88.dp).onGloballyPositioned{incomeBounds=it.boundsInRoot()}.clickable(enabled=selected!=null){selected?.let{vm.place(it,true);selectedId=null}},shape=RoundedCornerShape(bottomStart=55.dp,bottomEnd=55.dp,topStart=12.dp,topEnd=12.dp),color=if(selected!=null)Color(0xFFEAF7FF)else Color(0xFFF8FAFC),border=androidx.compose.foundation.BorderStroke(4.dp,Color(0xFF60A5FA)),shadowElevation=7.dp){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("💰 ДОХОДЫ",fontSize=14.sp,fontWeight=FontWeight.Black,color=Color(0xFF1D4ED8));Text("${s.income} монет",fontSize=16.sp,fontWeight=FontWeight.Black);Text(if(selected!=null)"Отпусти здесь" else "Деньги приходят",fontSize=9.sp,color=Color(0xFF64748B))}};Surface(Modifier.align(Alignment.CenterEnd).offset(y=(beamAngle*.62f).dp).width(137.dp).height(88.dp).onGloballyPositioned{expenseBounds=it.boundsInRoot()}.clickable(enabled=selected!=null){selected?.let{vm.place(it,false);selectedId=null}},shape=RoundedCornerShape(bottomStart=55.dp,bottomEnd=55.dp,topStart=12.dp,topEnd=12.dp),color=if(selected!=null)Color(0xFFFFEEEE)else Color(0xFFF8FAFC),border=androidx.compose.foundation.BorderStroke(4.dp,Color(0xFFF87171)),shadowElevation=7.dp){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("🛒 РАСХОДЫ",fontSize=14.sp,fontWeight=FontWeight.Black,color=Color(0xFFB91C1C));Text("${s.expenses} монет",fontSize=16.sp,fontWeight=FontWeight.Black);Text(if(selected!=null)"Отпусти здесь" else "Деньги уходят",fontSize=9.sp,color=Color(0xFF64748B))}}}}
    }
    if(s.cards.isNotEmpty()){Text("КОЛОДА • зажми и перетащи на весы",fontSize=13.sp,fontWeight=FontWeight.Black,color=Color(0xFF263A65));LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp),contentPadding=PaddingValues(vertical=4.dp)){items(s.cards,key={it.id}){card->val active=card.id==selectedId;var drag by remember(card.id){mutableStateOf(Offset.Zero)};var origin by remember(card.id){mutableStateOf(Offset.Zero)};var size by remember(card.id){mutableStateOf(androidx.compose.ui.unit.IntSize.Zero)};val dragging=drag!=Offset.Zero;Surface(Modifier.width(92.dp).height(100.dp).zIndex(if(dragging)20f else 0f).graphicsLayer{translationX=drag.x;translationY=drag.y;scaleX=if(dragging)1.08f else 1f;scaleY=if(dragging)1.08f else 1f;shadowElevation=if(dragging)24f else 0f}.onGloballyPositioned{origin=it.boundsInRoot().topLeft;size=it.size}.pointerInput(card.id){detectDragGesturesAfterLongPress(onDragStart={selectedId=card.id},onDrag={change,amount->change.consume();drag+=amount},onDragCancel={drag=Offset.Zero},onDragEnd={val center=origin+drag+Offset(size.width/2f,size.height/2f);when{incomeBounds.contains(center)->vm.place(card,true);expenseBounds.contains(center)->vm.place(card,false)};selectedId=null;drag=Offset.Zero})}.clickable{selectedId=card.id},shape=RoundedCornerShape(16.dp),color=if(active)Color(0xFFFFF0B5)else Color.White,border=androidx.compose.foundation.BorderStroke(if(active)4.dp else 1.dp,if(active)Color(0xFFF59E0B)else Color(0xFFD6DFEC)),shadowElevation=5.dp){Column(Modifier.padding(6.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.SpaceEvenly){Text(when(card.id){"work"->"💼";"reward"->"🏆";"gift"->"🎁";"food"->"🍗";"rent"->"🏠";"transport"->"🚌";"medicine"->"❤";"toy"->"🧸";else->"★"},fontSize=25.sp);Text(card.title,fontSize=10.sp,fontWeight=FontWeight.Bold,textAlign=androidx.compose.ui.text.style.TextAlign.Center,maxLines=2);Text("${card.amount} мон.",fontSize=12.sp,fontWeight=FontWeight.Black,color=Color(0xFF263A65))}}}}
        FinnySpeechCard(if(selected==null)"Зажми карточку и перетащи её: доход — на левую чашу, расход — на правую." else "Куда относится «${selected.title}»: деньги приходят или уходят?")
    }else{FinnySpeechCard("Все карточки на месте, а баланс не ушёл в минус. Подводим итог…")}
}}

@Composable fun PrioritiesScreen(onBack:()->Unit,onDone:(Int)->Unit,vm:PrioritiesViewModel=hiltViewModel()){val s by vm.state.collectAsStateWithLifecycle();if(s.message.isNotEmpty()&&s.message!="Хороший выбор!")FeedbackDialog("Почему так?",s.message,vm::clearMessage);val card=s.cards.firstOrNull();var nowBounds by remember{mutableStateOf(Rect.Zero)};var laterBounds by remember{mutableStateOf(Rect.Zero)};var noBounds by remember{mutableStateOf(Rect.Zero)};var drag by remember(card?.id){mutableStateOf(Offset.Zero)};var cardOrigin by remember(card?.id){mutableStateOf(Offset.Zero)};var cardSize by remember(card?.id){mutableStateOf(androidx.compose.ui.unit.IntSize.Zero)};GameFrame("Приоритеты","Перетаскивай покупки в нужный контейнер",s.level,onBack){
    LaunchedEffect(s.cards.isEmpty()){if(s.cards.isEmpty()){kotlinx.coroutines.delay(650);vm.finish(onDone)}}
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){GameStat("₽","Бюджет",s.budget.toString(),Color(0xFFFFF0C9),Modifier.weight(1f));GameStat("✓","Запланировано",s.placed.toString(),Color(0xFFE6F0FF),Modifier.weight(1f));GameStat("=","Свободно",(s.budget-s.placed).toString(),Color(0xFFDFF7EB),Modifier.weight(1f))}
    if(card!=null){Surface(Modifier.fillMaxWidth().zIndex(if(drag!=Offset.Zero)20f else 0f).graphicsLayer{translationX=drag.x;translationY=drag.y;scaleX=if(drag!=Offset.Zero)1.06f else 1f;scaleY=if(drag!=Offset.Zero)1.06f else 1f}.onGloballyPositioned{cardOrigin=it.boundsInRoot().topLeft;cardSize=it.size}.pointerInput(card.id){detectDragGesturesAfterLongPress(onDrag={change,amount->change.consume();drag+=amount},onDragCancel={drag=Offset.Zero},onDragEnd={val center=cardOrigin+drag+Offset(cardSize.width/2f,cardSize.height/2f);when{nowBounds.contains(center)->vm.place(card,PriorityZone.NOW);laterBounds.contains(center)->vm.place(card,PriorityZone.LATER);noBounds.contains(center)->vm.place(card,PriorityZone.NO)};drag=Offset.Zero})},shape=RoundedCornerShape(28.dp),color=Color.White,shadowElevation=9.dp){Column(Modifier.padding(18.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(6.dp)){Text("ЗАЖМИ И ПЕРЕТАЩИ",fontSize=12.sp,fontWeight=FontWeight.Black,color=Color(0xFFE08A2C));Text(when(card.id){"food"->"🍲";"water"->"💧";"medicine"->"❤";"rent"->"🏠";"toy"->"🧸";"book"->"📚";"ball"->"⚽";"console"->"🎮";else->"★"},fontSize=59.sp);Text(card.title,fontSize=25.sp,fontWeight=FontWeight.Black,color=Color(0xFF263A65));Text("${card.price} монет",fontSize=20.sp,fontWeight=FontWeight.Black,color=Color(0xFFB86E00));Text("Отпусти карточку над нужным контейнером",fontSize=12.sp,color=Color(0xFF68748A))}}
        Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){
            listOf(
                PriorityZone.NOW to Triple(Icons.Default.CheckCircle,"Сейчас",Color(0xFF43AD75)),
                PriorityZone.LATER to Triple(Icons.Default.Schedule,"Потом",Color(0xFFE9A437)),
                PriorityZone.NO to Triple(Icons.Default.Block,"Пропустить",Color(0xFFE45F68))
            ).forEach{(zone,style)->Surface(Modifier.weight(1f).height(103.dp).onGloballyPositioned{when(zone){PriorityZone.NOW->nowBounds=it.boundsInRoot();PriorityZone.LATER->laterBounds=it.boundsInRoot();PriorityZone.NO->noBounds=it.boundsInRoot()}}.clickable{vm.place(card,zone)},shape=RoundedCornerShape(20.dp),color=style.third,shadowElevation=6.dp,border=androidx.compose.foundation.BorderStroke(2.dp,Color.White.copy(.85f))){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Icon(style.first,null,Modifier.size(29.dp),tint=Color.White);Spacer(Modifier.height(5.dp));Text(style.second,color=Color.White,fontSize=12.sp,fontWeight=FontWeight.Black,maxLines=1);Text(when(zone){PriorityZone.NOW->"Нужно";PriorityZone.LATER->"Желание";PriorityZone.NO->"Лишнее"},color=Color.White.copy(.78f),fontSize=10.sp)}}}
        }
        Text("Осталось решений: ${s.cards.size}",Modifier.fillMaxWidth(),textAlign=androidx.compose.ui.text.style.TextAlign.Center,fontWeight=FontWeight.Bold,color=Color(0xFF53627A))
    }else{FinnySpeechCard("Все покупки распределены, важное оплачено, а бюджет сохранён. Подводим итог…")}
}}

private data class FallingSaving(val id:Int,val coin:Boolean,val value:Int,val icon:String,val x:Float,val y:Float)

@Composable fun PiggyBankScreen(onBack:()->Unit,onDone:(Int)->Unit,vm:PiggyBankViewModel=hiltViewModel()){val s by vm.state.collectAsStateWithLifecycle();val percent=(s.collected.toFloat()/s.totalCoins).coerceIn(0f,1f);val falling=remember(s.level){mutableStateListOf<FallingSaving>()};var pigX by rememberSaveable(s.level){mutableFloatStateOf(.38f)};var feedback by rememberSaveable(s.level){mutableStateOf("Веди копилку пальцем. Лови монеты, а сладости и игрушки пропускай.")};val desires=listOf("🍦","🧸","🎮","🍭","⚽");GameFrame("Копилка","Лови монеты движущейся копилкой",s.level,onBack){
    LaunchedEffect(s.running,s.seconds){if(s.running){kotlinx.coroutines.delay(1000);vm.tick()}}
    LaunchedEffect(s.running){
        if(s.running){
            falling.clear();var id=0;var spawnClock=620L
            while(s.running){
                kotlinx.coroutines.delay(16);spawnClock+=16
                if(spawnClock>=760){spawnClock=0;val coin=id%10<7;val value=listOf(1,1,2,2,5,5)[(id+s.level)%6];falling+=FallingSaving(id,coin,value,desires[(id+s.level)%desires.size],((id*37+s.level*13)%82)/100f+.04f,-.14f);id++}
                val next=ArrayList<FallingSaving>(falling.size)
                falling.forEach{o->val moved=o.copy(y=o.y+.0072f+s.level*.00012f);val caught=moved.y in .72f..88f&&kotlin.math.abs((moved.x+.06f)-(pigX+.12f))<.16f;when{caught->{if(moved.coin){vm.coin(moved.value);feedback="Отлично! +${moved.value} монет в копилку."}else{vm.catchTemptation();feedback="${moved.icon} можно купить позже. Не лови предметы-искушения."}};moved.y>1.05f->{if(moved.coin)vm.missCoin()else vm.temptation()};else->next+=moved}}
                falling.clear();falling.addAll(next)
            }
        }
    }
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){GameStat("₽","Собрано","${s.collected}/${s.totalCoins}",Color(0xFFFFF0C9),Modifier.weight(1f));GameStat("⏱","Время","${s.seconds} с",Color(0xFFE6F0FF),Modifier.weight(1f));GameStat("✕","Искушения","${s.temptations}/3",Color(0xFFFFE2E1),Modifier.weight(1f))}
    FinnyProgressTrack(percent,Modifier.fillMaxWidth(),color=Color(0xFFFFB92F),height=13.dp)
    if(s.running){Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(28.dp),color=Color(0xFF34275C),shadowElevation=10.dp){BoxWithConstraints(Modifier.fillMaxWidth().height(345.dp).background(Brush.verticalGradient(listOf(Color(0xFF31275B),Color(0xFF67529B),Color(0xFFB99ADB)))).pointerInput(Unit){detectDragGestures(onDragStart={p->pigX=(p.x/size.width-.12f).coerceIn(0f,.76f)},onDrag={change,amount->change.consume();pigX=(pigX+amount.x/size.width).coerceIn(0f,.76f)})}){
        repeat(22){i->Box(Modifier.offset(x=((i*47)%100/100f*maxWidth.value).dp,y=((i*71)%100/100f*300).dp).size(if(i%3==0)3.dp else 2.dp).background(Color.White.copy(.65f),CircleShape))}
        falling.forEach{o->if(o.coin)Surface(Modifier.offset(x=(maxWidth-52.dp)*o.x,y=(310.dp)*o.y).size(48.dp),shape=CircleShape,color=Color(0xFFFFC83D),border=androidx.compose.foundation.BorderStroke(3.dp,Color(0xFFFFEC9A)),shadowElevation=7.dp){Box(contentAlignment=Alignment.Center){Text("${o.value}",fontSize=18.sp,fontWeight=FontWeight.Black,color=Color(0xFF805000))}}else Surface(Modifier.offset(x=(maxWidth-52.dp)*o.x,y=(310.dp)*o.y).size(48.dp),shape=RoundedCornerShape(15.dp),color=Color(0xFFFFE7F0),border=androidx.compose.foundation.BorderStroke(2.dp,Color(0xFFFF8DB4)),shadowElevation=6.dp){Box(contentAlignment=Alignment.Center){Text(o.icon,fontSize=27.sp)}}}
        Surface(Modifier.offset(x=(maxWidth-106.dp)*pigX,y=271.dp).size(width=106.dp,height=69.dp),shape=RoundedCornerShape(31.dp),color=Color(0xFFFF78A8),border=androidx.compose.foundation.BorderStroke(4.dp,Color.White),shadowElevation=10.dp){Box(contentAlignment=Alignment.Center){Text("🐷",fontSize=48.sp);Text("МОНЕТЫ",Modifier.align(Alignment.TopCenter).offset(y=(-7).dp),fontSize=8.sp,fontWeight=FontWeight.Black,color=Color.White)}}
        Text("← веди копилку пальцем →",Modifier.align(Alignment.TopCenter).padding(top=7.dp),fontSize=11.sp,color=Color.White.copy(.9f),fontWeight=FontWeight.Bold)
    }}}
    else if(s.processed==0){Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(28.dp),color=Color(0xFF34275C),shadowElevation=8.dp){Column(Modifier.fillMaxWidth().padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("🐷",fontSize=86.sp);Text("Собери ${s.totalCoins} монет",fontSize=22.sp,fontWeight=FontWeight.Black,color=Color.White);Text("Можно пропустить монету, но не лови три лишних покупки.",textAlign=androidx.compose.ui.text.style.TextAlign.Center,color=Color.White.copy(.82f))}}}
    Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),color=Color(0xFFFFE9B9),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xFFFFC45C))){Text(feedback,Modifier.padding(12.dp),fontSize=14.sp,fontWeight=FontWeight.SemiBold,color=Color(0xFF674910))}
    if(!s.running&&s.processed==0)FinnyButton("Начать игру",vm::start,modifier=Modifier.fillMaxWidth())
    if(!s.running&&s.processed>0){val success=s.collected>=s.totalCoins;Text(if(success)"Цель собрана! ${s.collected} монет в копилке." else if(s.temptations>=3)"Поймано три искушения. Пропускай игрушки и сладости." else "Время вышло: ${s.collected} из ${s.totalCoins} монет.",fontSize=17.sp,fontWeight=FontWeight.Bold,color=Color(0xFF263A65));if(success)FinnyButton("Забрать результат",{vm.finish(onDone)},modifier=Modifier.fillMaxWidth())else OutlinedButton(onClick=vm::start,modifier=Modifier.fillMaxWidth().heightIn(min=52.dp)){Text("Попробовать ещё",fontWeight=FontWeight.Bold)}}
}}

@OptIn(ExperimentalLayoutApi::class)
@Composable fun GoalScreen(onBack:()->Unit,onDone:(Int)->Unit,vm:GoalGameViewModel=hiltViewModel()){val s by vm.state.collectAsStateWithLifecycle();val goalError=s.message.startsWith("Свободно")||s.message.startsWith("Чтобы")||s.message.startsWith("Сначала");if(goalError)FeedbackDialog("Проверь сумму",s.message,vm::clearMessage);GameFrame("Цель","Собери мечту по шагам",s.level,onBack){
    FinnyCard(Modifier.fillMaxWidth()){
        Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(s.goal,fontSize=22.sp,fontWeight=FontWeight.Black,color=Color(0xFF263A65));Text("${s.preview} / ${s.cost} монет",fontSize=16.sp,color=Color(0xFF667085))};Text(when(s.goal){"Игрушка"->"🧸";"Домик"->"🏠";else->"🏰"},fontSize=54.sp)}
        FinnyProgressTrack(s.preview.toFloat()/s.cost,Modifier.fillMaxWidth(),color=Color(0xFFFFB52E),height=14.dp)
        Text("До цели осталось ${(s.cost-s.preview).coerceAtLeast(0)} монет",fontWeight=FontWeight.Bold,color=Color(0xFF53627A))
    }
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){GameStat("💰","Доход",s.incomes.first().toString(),Color(0xFFFFF0D0),Modifier.weight(1f));GameStat("📦","Обязательно",s.expenses.first().toString(),Color(0xFFFFE8D6),Modifier.weight(1f));GameStat("✓","Свободно",s.free.toString(),Color(0xFFDFF8EE),Modifier.weight(1f))}
    Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(24.dp),color=Color.White,shadowElevation=7.dp){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Сколько положить в копилку?",fontSize=18.sp,fontWeight=FontWeight.Black,color=Color(0xFF263A65));FlowRow(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){s.options.forEach{a->FilterChip(selected=s.selected==a,onClick={vm.select(a)},enabled=a<=s.free,label={Text("+$a",fontWeight=FontWeight.Black)},colors=FilterChipDefaults.filterChipColors(selectedContainerColor=Color(0xFFFFD66B)))}};Text(if(s.selected>0)"После вклада останется ${s.free-s.selected} монет на текущие расходы." else "Выбери сумму, которая не превышает свободный остаток.",fontSize=14.sp,color=Color(0xFF53627A));FinnyButton("В копилку ▶",{vm.confirm{vm.finish(onDone)}},enabled=s.selected>0,modifier=Modifier.fillMaxWidth())}}
}}

@Composable fun ShopScreen(onBack:()->Unit,onDone:(Int)->Unit,vm:ShopGameViewModel=hiltViewModel()){val s by vm.state.collectAsStateWithLifecycle();val shopError=s.message.startsWith("Не хватает")||s.message.startsWith("Подумай")||s.message.startsWith("Этот товар");if(shopError)FeedbackDialog("Проверь покупку",s.message,vm::clearMessage);GameFrame("Магазин","Сначала добавь обязательный товар",s.level,onBack){
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){GameStat("₽","Бюджет",s.budget.toString(),Color(0xFFFFF1C9),Modifier.weight(1f));GameStat("#","В чеке",s.total.toString(),Color(0xFFE8F1FF),Modifier.weight(1f));GameStat("✓","Остаток",s.left.toString(),Color(0xFFDFF8EE),Modifier.weight(1f))}
    Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(25.dp),color=Color(0xFFF0F5FB),border=androidx.compose.foundation.BorderStroke(2.dp,Color(0xFF9CAFC8)),shadowElevation=7.dp){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("🏪 ВИТРИНА — нажми на товар",fontWeight=FontWeight.Black,color=Color(0xFF53627A));LazyRow(horizontalArrangement=Arrangement.spacedBy(9.dp)){items(s.items){i->val inCart=i in s.cart;Surface(Modifier.width(112.dp).clickable{if(inCart)vm.remove(i)else vm.add(i)},shape=RoundedCornerShape(18.dp),color=if(inCart)Color(0xFFDFF8EE) else Color.White,border=androidx.compose.foundation.BorderStroke(if(inCart)3.dp else 1.dp,if(inCart)Color(0xFF36A36F) else Color(0xFFD5DEEC)),shadowElevation=3.dp){Column(Modifier.padding(10.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(i.icon,fontSize=34.sp);Text(i.title,fontSize=12.sp,fontWeight=FontWeight.Bold,maxLines=2);Text("${i.price} мон.",fontWeight=FontWeight.Black,color=Color(0xFFB56A00));Text(if(i.required)"Нужно" else "Можно",fontSize=11.sp,color=if(i.required)Color(0xFF188653) else Color(0xFF667085))}}}}}}
    Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(25.dp),color=Color(0xFF1F3658),shadowElevation=8.dp){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Text("🛒 ЛЕНТА КАССЫ • ${s.cart.size} товаров",color=Color.White,fontWeight=FontWeight.Black);if(s.cart.isEmpty())Box(Modifier.fillMaxWidth().height(84.dp).background(Color(0xFF10233F),RoundedCornerShape(15.dp)),contentAlignment=Alignment.Center){Text("Лента пуста — выбери товары",color=Color(0xFFB8C7DB))}else LazyRow(Modifier.fillMaxWidth().background(Color(0xFF10233F),RoundedCornerShape(15.dp)).padding(8.dp),horizontalArrangement=Arrangement.spacedBy(7.dp)){items(s.cart){i->AssistChip(onClick={vm.remove(i)},label={Text("${i.icon} ${i.price} ×")})}}}}
    Text("Сначала положи то, что питомцу необходимо. Покупки по желанию бери только на оставшиеся монеты.",fontSize=15.sp,fontWeight=FontWeight.SemiBold,color=Color(0xFF3F4E69))
    FinnyButton("Оплатить покупки",{vm.pay(onDone)},modifier=Modifier.fillMaxWidth())
}}

@OptIn(ExperimentalLayoutApi::class)
@Composable fun ChangeScreen(onBack:()->Unit,onDone:(Int)->Unit,vm:ChangeGameViewModel=hiltViewModel()){val s by vm.state.collectAsStateWithLifecycle();if(s.message.isNotEmpty())FeedbackDialog("Проверим сдачу",s.message,vm::clearMessage);GameFrame("Сдача","Собери правильную сумму",s.task,onBack){
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){GameStat("🏷","Цена",s.price.toString(),Color(0xFFFFE3E6),Modifier.weight(1f));GameStat("💵","Оплачено",s.paid.toString(),Color(0xFFE1F4FF),Modifier.weight(1f));GameStat("🎯","Вернуть",s.expected.toString(),Color(0xFFFFF0C9),Modifier.weight(1f))}
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){
        Surface(Modifier.weight(.8f),shape=RoundedCornerShape(20.dp),color=Color(0xFF152A48),shadowElevation=7.dp){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text("ЧЕК",color=Color(0xFF9FD8FF),fontWeight=FontWeight.Black);Text(s.itemName,color=Color.White,fontWeight=FontWeight.Bold);HorizontalDivider(color=Color.White.copy(.2f));Text("Стоимость: ${s.price}",color=Color.White);Text("К возврату: ${s.expected}",color=Color(0xFF4DDAFF),fontSize=19.sp,fontWeight=FontWeight.Black)}}
        Surface(Modifier.weight(1.2f),shape=RoundedCornerShape(20.dp),color=Color(0xFFEAF2FB),border=androidx.compose.foundation.BorderStroke(2.dp,Color(0xFF8EA5BE))){Column(Modifier.padding(12.dp)){Text("СДАЧА В ЛОТКЕ",fontWeight=FontWeight.Black,color=Color(0xFF263A65));Text("${s.total} монет",fontSize=24.sp,fontWeight=FontWeight.Black,color=Color(0xFF347FD0));Box(Modifier.fillMaxWidth().height(76.dp).background(Color(0xFF879BB2),RoundedCornerShape(14.dp)).padding(6.dp)){if(s.selected.isEmpty())Text("Набери монеты",Modifier.align(Alignment.Center),color=Color.White)else FlowRow(horizontalArrangement=Arrangement.spacedBy(4.dp)){s.selected.forEach{v->Surface(Modifier.clickable{vm.remove(v)},shape=CircleShape,color=coinColor(v),shadowElevation=3.dp){Text("$v",Modifier.padding(8.dp),fontWeight=FontWeight.Black)}}}}}}
    }
    Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(22.dp),color=Color(0xFF263A59)){Column(Modifier.padding(12.dp)){Text("МОНЕТЫ КАССЫ — нажми, чтобы добавить",color=Color.White,fontWeight=FontWeight.Black);FlowRow(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceEvenly){s.available.distinct().sorted().forEach{v->Surface(Modifier.padding(3.dp).size(52.dp).clickable{vm.add(v)},shape=CircleShape,color=coinColor(v),border=androidx.compose.foundation.BorderStroke(2.dp,Color.White),shadowElevation=5.dp){Box(contentAlignment=Alignment.Center){Text("$v",fontWeight=FontWeight.Black,fontSize=17.sp,color=Color(0xFF402D21))}}}}}}
    Text("Цена ${s.price}, оплата ${s.paid}. Набери в лотке ровно ${s.expected} монет.",fontSize=15.sp,fontWeight=FontWeight.SemiBold,color=Color(0xFF3F4E69))
    FinnyButton("✓ Выдать сдачу",{vm.check(onDone)},modifier=Modifier.fillMaxWidth())
}}

@Composable private fun GameStat(icon:String,label:String,value:String,color:Color,modifier:Modifier=Modifier){Surface(modifier.heightIn(min=68.dp),shape=RoundedCornerShape(18.dp),color=color,border=androidx.compose.foundation.BorderStroke(1.dp,Color.White),shadowElevation=4.dp){Column(Modifier.fillMaxWidth().padding(horizontal=5.dp,vertical=8.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("$icon $label",fontSize=10.sp,lineHeight=12.sp,fontWeight=FontWeight.Bold,color=Color(0xFF53627A),maxLines=2,textAlign=androidx.compose.ui.text.style.TextAlign.Center,overflow=TextOverflow.Ellipsis);Text(value,fontSize=19.sp,fontWeight=FontWeight.Black,color=Color(0xFF263A65),maxLines=1,softWrap=false)}}}
@Composable private fun FinnySpeechCard(text:String){Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(21.dp),color=Color(0xFFFFE9B9),border=androidx.compose.foundation.BorderStroke(2.dp,Color(0xFFFFC45C))){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Text("🐾",fontSize=29.sp);Spacer(Modifier.width(9.dp));Text(text,Modifier.weight(1f),fontSize=15.sp,fontWeight=FontWeight.SemiBold,color=Color(0xFF674910))}}}
private fun coinColor(value:Int)=when(value){1->Color(0xFFF4B84E);2->Color(0xFFFFD34D);5->Color(0xFFE7A92E);10->Color(0xFFFF9A66);20->Color(0xFF79A8FF);else->Color(0xFFF062A6)}
